applications/entry/urls.py
from django.urls import path

from . import views
app_name = "entry_app"

urlpatterns = [
    path(
        'entries/',
        views.EntryListView.as_view(),
        name='entry-list',        
    ),
    path(
        'entry/<slug>/',
        views.EntryDetailView.as_view(),
        name='entry-detail',        
    ),
]

applications/home/urls.py
from django.urls import path

from . import views
app_name = "home_app"

urlpatterns = [
    path(
        '',
        views.HomePageView.as_view(),
        name='index',        
    ),
    path(
        'register-subscription',
        views.SubscribersCreateView.as_view(),
        name='add-subscription',        
    ),
    path(
        'contact',
        views.ContactCreateView.as_view(),
        name='add-contact',        
    ),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
# SEO
from django.contrib.sitemaps.views import sitemap
from applications.home.sitemap import (
    EntrySitemap,
    Sitemap,
)

urlpatterns_main = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entry.urls')),
    re_path('', include('applications.favorites.urls')),
    #Url's for ckeditor
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#objeto site map que genera xml
# Site object map generate xml
sitemaps = {
    'site':Sitemap(
        [
            'home_app:index'
        ]
    ),
    'entradas': EntrySitemap
}

urlpatterns_sitemap = [
    path(
        'sitemap.xml', 
        sitemap, 
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    )
]

urlpatterns = urlpatterns_main + urlpatterns_sitemap

applications/home/models.py
from django.db import models
#
from model_utils.models import TimeStampedModel

""" Model for homepage data """

class Home(TimeStampedModel):
    
    title = models.CharField( 
        'Name',    
        max_length=30
    )
    description = models.TextField()
    about_title = models.CharField(
        'Title us',
        max_length=50
    )
    about_text = models.TextField()
    contact_email = models.EmailField(
        'Contact email',
        blank=True,
        null=True
    )    
    phone = models.CharField(
        'Contact phone',
        max_length=20
    )

    class Meta:
        verbose_name = 'Homepage'
        verbose_name_plural = 'Homepage'

    def __str__(self):
        return self.title

""" Model for subscriptions """

class Subscribers(TimeStampedModel):

    email = models.EmailField()

    class Meta:
        verbose_name = 'Subscriber'
        verbose_name_plural = 'Subscribers'

    def __str__(self):
        return self.email

""" Contact form """

class Contact(TimeStampedModel):

    full_name = models.CharField(
        'Names',
        max_length=60
    )
    email = models.EmailField()
    message = models.TextField()

    class Meta:
        verbose_name = 'Contact'
        verbose_name_plural = 'Messages'

    def __str__(self):
        return self.full_name

applications/home/forms.py
from django import forms
from .models import Subscribers, Contact

class SubscribersForm(forms.ModelForm):

    class Meta:
        model = Subscribers
        fields = (
            'email',
        )
        widgets = {
            'email': forms.EmailInput(
                attrs={
                    'placeholder': 'Correo Electrónico',
                }
            ),
        }

class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = ('__all__')

applications/home/views.py
import datetime
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse

from django.views.generic import (
    TemplateView,
    CreateView
)

# Model Entry
from applications.entry.models import Entry

# Model Home
from .models import Home

# Forms
from .forms import SubscribersForm, ContactForm

class HomePageView(TemplateView):
    template_name = "home/index.html"
    
    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        # Load home
        context["home"] = Home.objects.latest('created')
        # Cover page text
        context["coverpage"] = Entry.objects.entry_in_coverpage()
        # Context for articles in home
        context["entry_home"] = Entry.objects.entry_in_home()
        # Entry recents
        context["entry_recents"] = Entry.objects.entry_recents()       
        # Send subscription form 
        context["form"] = SubscribersForm
        return context


class SubscribersCreateView(CreateView):
    form_class = SubscribersForm
    success_url = '.'
    
class ContactCreateView(CreateView):
    form_class = ContactForm
    success_url = '.'

    

templates/home/base_home.html
{% extends "base.html" %}

{% load  static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/myblog.css' %}">
{% endblock css %}

{% block js %}

{% endblock js %}

templates/home/index.html
<!-- head para PC -->
{% extends "home/base_home.html" %}

{% load  static %}

{% block title %}
{{  home.title }}
{% endblock title %}

{% block description %}
<meta name="description" content="{{ home.description }}">
{% endblock description %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <!-- primer bloque del home -->
    <div class="grid-x grid-margin-x" style="margin-top: 1em;">
        <!-- bloque de blog principal -->
        <div class="cell small-12 large-6">
            <div class="card" style="width: 100%;">
                <img src="{{ coverpage.image.url }}">
                <div class="card-section">
                  <h4><a href="{% url 'entry_app:entry-detail' coverpage.id %}">{{ coverpage.title }}</a></h4>
                  <p> {{ coverpage.resume | truncatechars:100}} </p>
                </div>
            </div>
        </div>
        <!-- FIN bloque de blog principal -->

        <!-- bloque de blog principal -->
        <div class="cell small-12 large-6 grid-x grid-margin-x">
            {% for entry in entry_home %}
            <div class="cell small-12 large-6">                
                <div class="card" style="width: 100%;">
                    <img src="{{ entry.image.url }}" style="height: 120px;">
                    <div class="card-section">
                        <h5>
                            <a href="{% url 'entry_app:entry-detail' entry.slug %}">{{ entry.title | truncatechars:46 }}</a>
                        </h5>
                    </div>
                </div>                
            </div>
            {% endfor %}
        </div>
        <!-- FIN bloque de blog principal -->
    </div>
    <!-- FIN del primer bloque home -->

    <!-- segundo bloque pantalla home -->
    <div class="grid-x align-center" style="margin-top: 1em;">
        <div class="cell small-12 large-10 callout secondary">
            <h5>{{ home.about_title }}</h5>
            <p>
                {{ home.about_text }}
            </p>

            <p>
                <button class="button" data-open="exampleModal2">Suscribirme</button>
            </p>

            <!-- This is the first modal -->
            <div class="reveal" id="exampleModal2" data-reveal style="width: 300px;">
                <p class="lead">Ingresa tu correo</p>
                <form class="grid-x grid-margin-x" method="POST" action="{% url 'home_app:add-subscription' %}"> {% csrf_token %}
                    <div class="cell small-12">
                        {{ form.email }}
                    </div>
                    <div class="cell small-12">
                        <button type="submit" class="success button">Suscribirme</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
    <!-- FIN segundo bloque pantalla home -->


    <!-- tercer bloque home -->
    <div class="grid-x grid-margin-x align-center">
        <h3 class="cell">Articulos Recientes:</h3>
        {% for entry in entry_recents %}
        <div class="cell small-6 large-4">
            <div class="card" style="width: 100%;">
                <img src="{{ entry.image.url }}">
                <div class="card-section">
                  <h4>
                    <a href="{% url 'entry_app:entry-detail' entry.slug %}">{{ entry.title | truncatechars:46 }}</a>
                  </h4>
                  <p>{{ entry.resume | truncatechars:100}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <!-- FIN tercer bloque -->
</div>
{% include "includes/footer.html" %}

{% endblock content %}