applications/entry/urls.py
from django.urls import path

from . import views
app_name = "entry_app"

urlpatterns = [
    path(
        'entries/',
        views.EntryListView.as_view(),
        name='entry-list',        
    ),
    path(
        'entry/<slug>/',
        views.EntryDetailView.as_view(),
        name='entry-detail',        
    ),
]

applications/favorites/urls.py
from django.urls import path

from . import views
app_name = "favorites_app"

urlpatterns = [
    path(
        'profile',
        views.UserPageView.as_view(),
        name='profile',        
    ),
    path(
        'add-entry/<pk>/',
        views.AddFavoritesView.as_view(),
        name='add-favorites',        
    ),
    path(
        'delete-favorites/?<pk>/', 
        views.FavoritesDeleteView.as_view(),
        name='delete-favorites',
    ),
]

applications/users/urls.py
from django.urls import path

from . import views
app_name = "users_app"

urlpatterns = [
    path(
        'register/',
        views.UserRegisterView.as_view(),
        name='user-register',        
    ),    
    path(
        'login/',
        views.LoginUser.as_view(),
        name='user-login',        
    ),
    path(
        'logout/',
        views.LogoutView.as_view(),
        name='user-logout',        
    ),
    path(
        'update/',
        views.UpdatePasswordView.as_view(),
        name='user-update',         
    ),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
# SEO
from django.contrib.sitemaps.views import sitemap
from applications.home.sitemap import (
    EntrySitemap,
    Sitemap,
)

urlpatterns_main = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entry.urls')),
    re_path('', include('applications.favorites.urls')),
    #Url's for ckeditor
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#objeto site map que genera xml
# Site object map generate xml
sitemaps = {
    'site':Sitemap(
        [
            'home_app:index'
        ]
    ),
    'entradas': EntrySitemap
}

urlpatterns_sitemap = [
    path(
        'sitemap.xml', 
        sitemap, 
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    )
]

urlpatterns = urlpatterns_main + urlpatterns_sitemap

applications/favorites/models.py
from django.db import models
from django.conf import settings
#
from model_utils.models import TimeStampedModel

from .managers import FavoritesManager

from applications.entry.models import Entry

""" Model for favorites """

class Favorites(TimeStampedModel):

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='user_favorites',
        on_delete=models.CASCADE,
    )
    entry = models.ForeignKey(
        Entry,
        related_name='entry_favorites',
        on_delete=models.CASCADE,
    )
    
    objects = FavoritesManager()

    class Meta:
        unique_together = ('user', 'entry')
        verbose_name = 'Favorite entry'
        verbose_name_plural = 'Favorite entries'

    def __str__(self):
        return self.entry.title

applications/favorites/views.py
from django.shortcuts import render
#
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
#
from django.views.generic import (
    View,
    ListView,
    DeleteView
)

#
from .models import Favorites
from applications.entry.models import Entry
from applications.home.models import Home

class UserPageView(ListView):
    template_name = "favorites/profile.html"
    context_object_name = "entries_user"
    login_url = reverse_lazy('users_app:user-login')

    def get_context_data(self, **kwargs):
        context = super(UserPageView, self).get_context_data(**kwargs)
        context["home"] = Home.objects.latest('created')
        return context

    def get_queryset(self):
        return Favorites.objects.entries_user(self.request.user)

class AddFavoritesView(LoginRequiredMixin, View):
    login_url = reverse_lazy('users_app:user-login')

    def post(self, request, *args, **kwargs):
        # Recover the user
        usuario = self.request.user
        entrada = Entry.objects.get(id=self.kwargs['pk'])
        # Register favorite
        Favorites.objects.create(
            user=usuario,
            entry=entrada,
        )

        return HttpResponseRedirect(
            reverse(
                'favorites_app:profile',
            )
        )

class FavoritesDeleteView(DeleteView):
    model = Favorites
    success_url = reverse_lazy('favorites_app:profile')

templates/favorites/base_favorites.html
{% extends "base.html" %}

{% load  static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/myblog.css' %}">
{% endblock css %}

{% block js %}

{% endblock js %}

templates/favorites/profile.html
<!-- head para PC -->
{% extends "favorites/base_favorites.html" %}

{% load  static %}

{% block title %}
{{  home.title }}
{% endblock title %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x grid-margin-x align-center" style="margin-top: 1em;">
        <!-- bloque de datos de usuario -->
        <div class="cell small-12 large-4">
            <div class="callout">
                <h5>{{ user.full_name }}</h5>
                <p>{{ user.email }} - {{ user.ocupation }} - {{ user.bdate_birth }}</p>
                <a href="#">Editar Datos</a>
                <p>
                    <a href="{% url 'users_app:user-logout' %}" class="clear button secondary">Cerrar sesión</a>
                </p>
            </div>
        </div>
        <!-- FIN bloque de datos de usuario -->


        <!-- bloque de articulos favoritos de usuario -->
        <div class="cell large-8 grid-x grid-margin-x align-center">
            {% for entry_user in entries_user %}
            <div class="cell small-12">
                <div class="card-favoritos">
                    <img class="card-favoritos-img" src="{{ entry_user.entry.image.url }}">
                    <div class="card-favoritos-body">
                        <h3 class="card-favoritos-body-titulo">{{ entry_user.entry.title }}</h3>
                        <p class="card-favoritos-body-text">{{ entry_user.entry.resume }}</p>
                        <form class="card-favoritos-body-actions" method="POST" action="{% url 'favorites_app:delete-favorites' entry_user.entry.slug  %}">{% csrf_token %}
                            <a class="button warning" href="{% url 'entry_app:entry-detail' entry_user.entry.slug %}">Ver</a>
                            <button type="submit" class="button alert">Eliminar</a>
                        </form>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <!-- FIN bloque de articulos favoritos de usuario -->
    </div>
</div>
{% include "includes/footer.html" %}

{% endblock content %}